name = "Galley"
uuid = "0b99cc74-af0a-4786-be99-594ac14242a4"
authors = ["Kyle Deeds <kdeeds@cs.washington.edu >"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Finch = "9177782c-1635-4eb9-9bfb-d9dfa25e6bce"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RewriteTools = "5969e224-3634-4c61-9f66-721b69e98b8a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SyntaxInterface = "b33eeca9-aacb-4496-a840-e75f1646a4fb"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[sources]
Finch = {url = "https://github.com/finch-tensor/Finch.jl.git", rev = "main"}

[compat]
AbstractTrees = "0.4"
AutoHashEquals = "2.2"
DataStructures = "0.18"
Finch = "0.6"
IterTools = "1"
PrecompileTools = "1"
RewriteTools = "0.2"
Statistics = "1"
SyntaxInterface = "0.2"
TermInterface = "2.0"
julia = "[1.10-2.0.0) "
